from typing import Dict, NamedTuple, Optional, List
from BaseClasses import ItemClassification
from .constants.item_groups import *
from .constants.jobs import *
from .constants.keys import *
from .constants.key_items import *
from .constants.maps import *
from .constants.mounts import *
from .constants.scholar_abilities import *
from .constants.summons import *
from .constants.teleport_stones import *
from .constants.region_passes import *
from .constants.display_regions import *

job_index_offset = 1
item_index_offset = 101
equipment_index_offset = 1001
summon_index_offset = 10001
scholar_index_offset = 100001
trap_index_offset = 1000001

class ItemData(NamedTuple):
    name: str
    category: str
    code: int
    classification: ItemClassification
    amount: Optional[int] = 1

region_equipment: Dict[str, List[ItemData]] = {
    MENU_DISPLAY_NAME: [],
    SPAWNING_MEADOWS_DISPLAY_NAME: [
        ItemData("Equipment - Burglars Glove", EQUIPMENT, 53 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cedar Staff", EQUIPMENT, 62 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cedar Wand", EQUIPMENT, 13 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cleaver", EQUIPMENT, 2 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Stabbers", EQUIPMENT, 63 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Stout Shield", EQUIPMENT, 45 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Squirrel Dung", EQUIPMENT, 85 + equipment_index_offset, ItemClassification.useful),
    ],
    DELENDE_DISPLAY_NAME: [
        ItemData("Equipment - Fervor Charm", EQUIPMENT, 48 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Bone Smasher", EQUIPMENT, 14 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Aggro Band", EQUIPMENT, 505 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cinquedea", EQUIPMENT, 393 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Scope Bit", EQUIPMENT, 226 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Red Hairpin", EQUIPMENT, 247 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Bracer", EQUIPMENT, 70 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Chartreuse", EQUIPMENT, 403 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cotton Hood", EQUIPMENT, 32 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Earring", EQUIPMENT, 79 + equipment_index_offset, ItemClassification.useful, 2),
        ItemData("Equipment - Looters Ring", EQUIPMENT, 54 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Mages Robe", EQUIPMENT, 21 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Protect Amulet", EQUIPMENT, 49 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Iron Sword", EQUIPMENT, 11 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Storm Hood", EQUIPMENT, 76 + equipment_index_offset, ItemClassification.useful),
    ],
    MERCURY_SHRINE_DISPLAY_NAME: [
        ItemData("Equipment - Contract", EQUIPMENT, 71 + equipment_index_offset, ItemClassification.useful),
    ],
    SOILED_DEN_DISPLAY_NAME: [
        ItemData("Equipment - Dodge Charm", EQUIPMENT, 39 + equipment_index_offset, ItemClassification.useful),
    ],
    THE_PALE_GROTTO_DISPLAY_NAME: [
        ItemData("Equipment - Poisonkiss", EQUIPMENT, 40 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Toothpick", EQUIPMENT, 42 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Storm Helm", EQUIPMENT, 74 + equipment_index_offset, ItemClassification.useful),
    ],
    SEASIDE_CLIFFS_DISPLAY_NAME: [
        ItemData("Equipment - Storm Cap", EQUIPMENT, 75 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Swimmers Top", EQUIPMENT, 81 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Bracer", EQUIPMENT, 70 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Headgear", EQUIPMENT, 30 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Scope Bit", EQUIPMENT, 226 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Jewel of Defense", EQUIPMENT, 50 + equipment_index_offset, ItemClassification.useful),
    ],
    YAMAGAWA_MA_DISPLAY_NAME: [
        ItemData("Equipment - Torpid Cuffs", EQUIPMENT, 331 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Iron Guard", EQUIPMENT, 68 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Broadsword", EQUIPMENT, 12 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Autumns Oath", EQUIPMENT, 234 + equipment_index_offset, ItemClassification.useful),
    ],
    PROVING_MEADOWS_DISPLAY_NAME: [
        ItemData("Equipment - Burglars Glove", EQUIPMENT, 53 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Battle Scythe", EQUIPMENT, 6 + equipment_index_offset, ItemClassification.useful),
    ],
    SKUMPARADISE_DISPLAY_NAME: [
        ItemData("Equipment - Help the Prince", EQUIPMENT, 89 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Stalwart Shield", EQUIPMENT, 88 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Sharp Sword", EQUIPMENT, 200 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Awake Ring", EQUIPMENT, 87 + equipment_index_offset, ItemClassification.useful, 2),
        ItemData("Equipment - Mana Ring", EQUIPMENT, 38 + equipment_index_offset, ItemClassification.useful),
    ],
    CAPITAL_SEQUOIA_DISPLAY_NAME: [
        ItemData("Equipment - Craftwork Sword", EQUIPMENT, 93 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Axe", EQUIPMENT, 94 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Dagger", EQUIPMENT, 95 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Rapier", EQUIPMENT, 96 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Katana", EQUIPMENT, 97 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Spear", EQUIPMENT, 98 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Scythe", EQUIPMENT, 99 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Bow", EQUIPMENT, 105 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Staff", EQUIPMENT, 100 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Wand", EQUIPMENT, 101 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Pages", EQUIPMENT, 102 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Shield", EQUIPMENT, 506 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Helm", EQUIPMENT, 508 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Mail", EQUIPMENT, 510 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Cap", EQUIPMENT, 512 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Vest", EQUIPMENT, 514 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Crown", EQUIPMENT, 516 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Craftwork Robe", EQUIPMENT, 518 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Fang Pendant", EQUIPMENT, 196 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Givers Ring", EQUIPMENT, 182 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Lucky Socks", EQUIPMENT, 498 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Lucky Briefs", EQUIPMENT, 499 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Learners Pin", EQUIPMENT, 492 + equipment_index_offset, ItemClassification.useful),
    ]
}

region_items: Dict[str, List[ItemData]] = {
    MENU_DISPLAY_NAME: [
        ItemData(WARRIOR_JOB, JOB, 0 + job_index_offset, ItemClassification.progression),
        ItemData(MONK_JOB, JOB, 5 + job_index_offset, ItemClassification.progression),
        ItemData(ROGUE_JOB, JOB, 2 + job_index_offset, ItemClassification.progression),
        ItemData(CLERIC_JOB, JOB, 4 + job_index_offset, ItemClassification.progression),
        ItemData(WIZARD_JOB, JOB, 3 + job_index_offset, ItemClassification.progression),
        ItemData(WARLOCK_JOB, JOB, 14 + job_index_offset, ItemClassification.progression),
        ItemData(FENCER_JOB, JOB, 1 + job_index_offset, ItemClassification.progression),
        ItemData(SHAMAN_JOB, JOB, 8 + job_index_offset, ItemClassification.progression),
        ItemData(SCHOLAR_JOB, JOB, 13 + job_index_offset, ItemClassification.progression),  # requirement for Grans subbasement
        ItemData(AEGIS_JOB, JOB, 10 + job_index_offset, ItemClassification.progression),
        ItemData(HUNTER_JOB, JOB, 7 + job_index_offset, ItemClassification.progression),
        ItemData(CHEMIST_JOB, JOB, 17 + job_index_offset, ItemClassification.progression),
        ItemData(REAPER_JOB, JOB, 6 + job_index_offset, ItemClassification.progression),
        ItemData(NINJA_JOB, JOB, 18 + job_index_offset, ItemClassification.progression),
        ItemData(NOMAD_JOB, JOB, 12 + job_index_offset, ItemClassification.progression),
        ItemData(DERVISH_JOB, JOB, 11 + job_index_offset, ItemClassification.progression),
        ItemData(BEATSMITH_JOB, JOB, 9 + job_index_offset, ItemClassification.progression),
        ItemData(SAMURAI_JOB, JOB, 20 + job_index_offset, ItemClassification.progression),
        ItemData(ASSASSIN_JOB, JOB, 19 + job_index_offset, ItemClassification.progression),
        ItemData(VALKYRIE_JOB, JOB, 15 + job_index_offset, ItemClassification.progression),
        ItemData(SUMMONER_JOB, JOB, 21 + job_index_offset, ItemClassification.progression),  # Required for summon fights; only job checked by NPCs
        ItemData(BEASTMASTER_JOB, JOB, 23 + job_index_offset, ItemClassification.progression),
        ItemData(WEAVER_JOB, JOB, 16 + job_index_offset, ItemClassification.progression),
        ItemData(MIMIC_JOB, JOB, 22 + job_index_offset, ItemClassification.progression),
        ItemData(PROGRESSIVE_QUINTAR_WOODWIND, MOUNT, 39 + item_index_offset, ItemClassification.progression, 3),  # Quintar Pass ID 7 & Quintar Flute ID 39 & Quintar Ocarina 115
        ItemData(IBEK_BELL, MOUNT, 50 + item_index_offset, ItemClassification.progression),
        ItemData(OWL_DRUM, MOUNT, 49 + item_index_offset, ItemClassification.progression),
        ItemData(PROGRESSIVE_SALMON_VIOLA, MOUNT, 48 + item_index_offset, ItemClassification.progression, 2),  # Salmon Violin ID 48 & Salmon Cello ID 114
        ItemData(PROGRESSIVE_MOUNT, MOUNT, 700 + item_index_offset, ItemClassification.progression, 7),
        ItemData(HOME_POINT_STONE, TELEPORT_STONE, 19 + item_index_offset, ItemClassification.useful),
        ItemData(SHAKU_SUMMON, SUMMON, 223 + summon_index_offset, ItemClassification.useful),
        ItemData(PAMOA_SUMMON, SUMMON, 224 + summon_index_offset, ItemClassification.useful),
        ItemData(GUABA_SUMMON, SUMMON, 225 + summon_index_offset, ItemClassification.useful),
        ItemData(NILTSI_SUMMON, SUMMON, 226 + summon_index_offset, ItemClassification.useful),
        ItemData(IOSKE_SUMMON, SUMMON, 227 + summon_index_offset, ItemClassification.useful),
        ItemData(COYOTE_SUMMON, SUMMON, 228 + summon_index_offset, ItemClassification.useful),
        ItemData(TIRA_SUMMON, SUMMON, 231 + summon_index_offset, ItemClassification.useful),
        ItemData(JUSES_SUMMON, SUMMON, 232 + summon_index_offset, ItemClassification.useful),
        ItemData(PAH_SUMMON, SUMMON, 234 + summon_index_offset, ItemClassification.useful),
        ItemData(ROOST, SCHOLAR_ABILITY, 25 + scholar_index_offset, ItemClassification.useful),
        ItemData(LUCKY_DICE, SCHOLAR_ABILITY, 70 + scholar_index_offset, ItemClassification.useful),
        ItemData(SUN_BATH, SCHOLAR_ABILITY, 101 + scholar_index_offset, ItemClassification.useful),
        ItemData(SLEEP_AURA, SCHOLAR_ABILITY, 186 + scholar_index_offset, ItemClassification.useful),
        ItemData(REGENERATE, SCHOLAR_ABILITY, 197 + scholar_index_offset, ItemClassification.useful),
        ItemData(REVERSE_POLARITY, SCHOLAR_ABILITY, 198 + scholar_index_offset, ItemClassification.progression),
        ItemData(BARRIER, SCHOLAR_ABILITY, 199 + scholar_index_offset, ItemClassification.useful),
        ItemData(MP_SICKLE, SCHOLAR_ABILITY, 200 + scholar_index_offset, ItemClassification.useful),
        ItemData(ADRENALINE, SCHOLAR_ABILITY, 202 + scholar_index_offset, ItemClassification.useful),
        ItemData(FIRE_BREATH, SCHOLAR_ABILITY, 205 + scholar_index_offset, ItemClassification.useful),
        ItemData(EXPLODE, SCHOLAR_ABILITY, 206 + scholar_index_offset, ItemClassification.useful),
        ItemData(WHIRLWIND, SCHOLAR_ABILITY, 207 + scholar_index_offset, ItemClassification.useful),
        ItemData(ATMOSHEAR, SCHOLAR_ABILITY, 213 + scholar_index_offset, ItemClassification.useful),
        ItemData(BUILD_LIFE, SCHOLAR_ABILITY, 245 + scholar_index_offset, ItemClassification.useful),
        ItemData(AERO, SCHOLAR_ABILITY, 264 + scholar_index_offset, ItemClassification.useful),
        ItemData(INSULT, SCHOLAR_ABILITY, 363 + scholar_index_offset, ItemClassification.useful),
        ItemData(INFUSION, SCHOLAR_ABILITY, 364 + scholar_index_offset, ItemClassification.useful),
        ItemData(OVERlOAD, SCHOLAR_ABILITY, 365 + scholar_index_offset, ItemClassification.useful),
        ItemData(REFLECTION, SCHOLAR_ABILITY, 366 + scholar_index_offset, ItemClassification.useful),
        ItemData(LIFEGIVER, SCHOLAR_ABILITY, 376 + scholar_index_offset, ItemClassification.useful),
        ItemData(SKELETON_KEY, KEY, 147 + item_index_offset, ItemClassification.progression),
    ],
    SPAWNING_MEADOWS_DISPLAY_NAME: [
        ItemData(SPAWNING_MEADOWS_PASS, PASS, 801 + item_index_offset, ItemClassification.progression),
        ItemData(SPAWNING_MEADOWS_MAP, MAP, 73 + item_index_offset, ItemClassification.useful),
        ItemData(BLACK_SQUIRREL, ITEM, 21 + item_index_offset, ItemClassification.progression, 4),
        ItemData("Item - Tonic Pouch", ITEM, 133 + item_index_offset, ItemClassification.useful, 2),
    ],
    DELENDE_DISPLAY_NAME: [
        ItemData(DELENDE_PASS, PASS, 802 + item_index_offset, ItemClassification.progression),
        ItemData(DELENDE_MAP, MAP, 74 + item_index_offset, ItemClassification.useful),
        ItemData(BASEMENT_MAP, MAP, 213 + item_index_offset, ItemClassification.useful),
        ItemData(DOG_BONE, ITEM, 6 + item_index_offset, ItemClassification.progression, 3),
        ItemData("Item - Gold Dust", ORE, 70 + item_index_offset, ItemClassification.useful),
        ItemData("Item - Tincture Pouch", ITEM, 135 + item_index_offset, ItemClassification.useful, 2),
        ItemData("Item - Fenix Juice Pouch", ITEM, 137 + item_index_offset, ItemClassification.useful),
        ItemData("Item - Flimsy Rod", TACKLE, 55 + item_index_offset, ItemClassification.progression),
        ItemData("Item - Plug Lure", TACKLE, 91 + item_index_offset, ItemClassification.progression),
    ],
    MERCURY_SHRINE_DISPLAY_NAME: [
        ItemData(MERCURY_SHRINE_PASS, PASS, 807 + item_index_offset, ItemClassification.progression),
        ItemData(MERCURY_SHRINE_MAP, MAP, 87 + item_index_offset, ItemClassification.useful),
        ItemData(MERCURY_STONE, TELEPORT_STONE, 13 + item_index_offset, ItemClassification.progression),
    ],
    SOILED_DEN_DISPLAY_NAME: [
        ItemData(SOILED_DEN_PASS, PASS, 803 + item_index_offset, ItemClassification.progression),
        ItemData(SOILED_DEN_MAP, MAP, 79 + item_index_offset, ItemClassification.useful),
        ItemData("Item - Tonic Pouch", ITEM, 133 + item_index_offset, ItemClassification.useful),
    ],
    THE_PALE_GROTTO_DISPLAY_NAME: [
        ItemData(THE_PALE_GROTTO_PASS, PASS, 804 + item_index_offset, ItemClassification.progression),
        ItemData(THE_PALE_GROTTO_MAP, MAP, 75 + item_index_offset, ItemClassification.useful),
        ItemData("Item - Tincture Pouch", ITEM, 135 + item_index_offset, ItemClassification.useful),
        ItemData("Item - Z-Potion Pouch", ITEM, 143 + item_index_offset, ItemClassification.useful),
    ],
    SEASIDE_CLIFFS_DISPLAY_NAME: [
        ItemData(SEASIDE_CLIFFS_PASS, PASS, 805 + item_index_offset, ItemClassification.progression),
        ItemData(SEASIDE_CLIFFS_MAP, MAP, 76 + item_index_offset, ItemClassification.useful),
        ItemData(CLAMSHELL, ITEM, 16 + item_index_offset, ItemClassification.progression, 0),
        ItemData("Item - Diamond Ore", ORE, 5 + item_index_offset, ItemClassification.useful),
        ItemData("Item - Tincture Pouch", ITEM, 135 + item_index_offset, ItemClassification.useful),
    ],
    DRAFT_SHAFT_CONDUIT_DISPLAY_NAME: [
        ItemData(DRAFT_SHAFT_CONDUIT_PASS, PASS, 806 + item_index_offset, ItemClassification.progression),
        ItemData(DRAFT_SHAFT_CONDUIT_MAP, MAP, 77 + item_index_offset, ItemClassification.useful),
        ItemData("Item - Tonic Pouch", ITEM, 133 + item_index_offset, ItemClassification.useful),
    ],
    YAMAGAWA_MA_DISPLAY_NAME: [
        ItemData(YAMAGAWA_MA_PASS, PASS, 808 + item_index_offset, ItemClassification.progression),
        ItemData(YAMAGAWA_MA_MAP, MAP, 80 + item_index_offset, ItemClassification.useful),
        ItemData("Item - Tonic Pouch", ITEM, 133 + item_index_offset, ItemClassification.useful),
    ],
    PROVING_MEADOWS_DISPLAY_NAME: [
        ItemData(PROVING_MEADOWS_PASS, PASS, 809 + item_index_offset, ItemClassification.progression),
        ItemData(PROVING_MEADOWS_MAP, MAP, 78 + item_index_offset, ItemClassification.useful),
        ItemData("Item - Tonic Pouch", ITEM, 133 + item_index_offset, ItemClassification.useful),
        ItemData("Item - Tincture Pouch", ITEM, 135 + item_index_offset, ItemClassification.useful),
    ],
    SKUMPARADISE_DISPLAY_NAME: [
        ItemData(SKUMPARADISE_PASS, PASS, 810 + item_index_offset, ItemClassification.progression),
        ItemData(SKUMPARADISE_MAP, MAP, 82 + item_index_offset, ItemClassification.useful),
        ItemData("Item - Tonic Pouch", ITEM, 133 + item_index_offset, ItemClassification.useful),
        ItemData("Item - Tincture Pouch", ITEM, 135 + item_index_offset, ItemClassification.useful),
    ],
    CAPITAL_SEQUOIA_DISPLAY_NAME: [
        ItemData(CAPITAL_SEQUOIA_PASS, PASS, 811 + item_index_offset, ItemClassification.progression),
        ItemData(CAPITAL_COURTYARD_MAP, MAP, 83 + item_index_offset, ItemClassification.useful),
        ItemData(CAPITAL_SEQUOIA_MAP, MAP, 84 + item_index_offset, ItemClassification.useful),
        ItemData(GAEA_STONE, TELEPORT_STONE, 23 + item_index_offset, ItemClassification.progression),
        ItemData(PROGRESSIVE_LUXURY_PASS, ITEM, 93 + item_index_offset, ItemClassification.progression, 2),
        ItemData(GARDENERS_KEY, KEY, 31 + item_index_offset, ItemClassification.progression),
        ItemData(COURTYARD_KEY, KEY, 33 + item_index_offset, ItemClassification.progression),
        ItemData(LUXURY_KEY, KEY, 36 + item_index_offset, ItemClassification.progression),
        ItemData(LOST_PENGUIN, ITEM, 24 + item_index_offset, ItemClassification.progression, 12),
        ItemData(DIGESTED_HEAD, ITEM, 17 + item_index_offset, ItemClassification.progression, 3),
        ItemData("Item - Tonic Pouch", ITEM, 133 + item_index_offset, ItemClassification.useful),
        ItemData("Item - Fenix Syrup Pouch", ITEM, 146 + item_index_offset, ItemClassification.useful),
    ]
}

region_shop_items: Dict[str, List[ItemData]] = {
    SPAWNING_MEADOWS_DISPLAY_NAME: [
        ItemData("Equipment - Short Sword", EQUIPMENT, 0 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Dirk", EQUIPMENT, 3 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Rapier", EQUIPMENT, 73 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Short Staff", EQUIPMENT, 5 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Ash Wand", EQUIPMENT, 8 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Buckler", EQUIPMENT, 44 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Chain Helm", EQUIPMENT, 25 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Breastplate", EQUIPMENT, 18 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Leather Cap", EQUIPMENT, 24 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Leather Outfit", EQUIPMENT, 17 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Hemp Hood", EQUIPMENT, 31 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Hemp Robe", EQUIPMENT, 19 + equipment_index_offset, ItemClassification.useful),
    ],
    DELENDE_DISPLAY_NAME: [
        ItemData("Equipment - Stout Shield", EQUIPMENT, 45 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Sturdy Helm", EQUIPMENT, 26 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Ring Mail", EQUIPMENT, 28 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Beret", EQUIPMENT, 27 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Studded Armor", EQUIPMENT, 35 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cotton Hood", EQUIPMENT, 32 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cotton Robe", EQUIPMENT, 20 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Earring", EQUIPMENT, 79 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Iron Sword", EQUIPMENT, 11 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Stabbers", EQUIPMENT, 63 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Stinger", EQUIPMENT, 1 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cedar Staff", EQUIPMENT, 62 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cedar Wand", EQUIPMENT, 13 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Bracer", EQUIPMENT, 70 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cleaver", EQUIPMENT, 2 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Fishgutter", EQUIPMENT, 77 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Moby Dick", EQUIPMENT, 51 + equipment_index_offset, ItemClassification.useful),
    ],
    SEASIDE_CLIFFS_DISPLAY_NAME: [
        ItemData("Equipment - Hand Axe", EQUIPMENT, 55 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Chopper", EQUIPMENT, 66 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Orylei", EQUIPMENT, 65 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Jewel of Defense", EQUIPMENT, 50 + equipment_index_offset, ItemClassification.useful),
    ],
    PROVING_MEADOWS_DISPLAY_NAME: [
        ItemData("Equipment - Dodge Charm", EQUIPMENT, 39 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Protect Amulet", EQUIPMENT, 49 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Bracer", EQUIPMENT, 70 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Earring", EQUIPMENT, 79 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Stout Shield", EQUIPMENT, 45 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Iron Guard", EQUIPMENT, 68 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Sturdy Helm", EQUIPMENT, 26 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Copper Helm", EQUIPMENT, 69 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Ring Mail", EQUIPMENT, 28 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Copper Suit", EQUIPMENT, 29 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Beret", EQUIPMENT, 27 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Headgear", EQUIPMENT, 30 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Studded Armor", EQUIPMENT, 35 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Leather Mail", EQUIPMENT, 36 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cotton Hood", EQUIPMENT, 32 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Holy Hat", EQUIPMENT, 33 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cotton Robe", EQUIPMENT, 20 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Mages Robe", EQUIPMENT, 21 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Iron Sword", EQUIPMENT, 11 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Broadsword", EQUIPMENT, 12 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Stabbers", EQUIPMENT, 63 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Shank", EQUIPMENT, 60 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Stinger", EQUIPMENT, 1 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Toothpick", EQUIPMENT, 42 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cedar Staff", EQUIPMENT, 62 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Gnarled Root", EQUIPMENT, 15 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cedar Wand", EQUIPMENT, 13 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Oak Wand", EQUIPMENT, 16 + equipment_index_offset, ItemClassification.useful),
    ],
    CAPITAL_SEQUOIA_DISPLAY_NAME: [
        ItemData("Equipment - Artisan Sword", EQUIPMENT, 157 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Sword", EQUIPMENT, 248 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Bigsword", EQUIPMENT, 249 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Axe", EQUIPMENT, 158 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Axe", EQUIPMENT, 251 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Bigaxe", EQUIPMENT, 250 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Dagger", EQUIPMENT, 159 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Dagger", EQUIPMENT, 269 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Rapier", EQUIPMENT, 160 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Rapier", EQUIPMENT, 252 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Katana", EQUIPMENT, 161 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Katana", EQUIPMENT, 253 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Spear", EQUIPMENT, 162 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Spear", EQUIPMENT, 254 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Scythe", EQUIPMENT, 163 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Bow", EQUIPMENT, 164 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Bow", EQUIPMENT, 256 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Staff", EQUIPMENT, 165 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Staff", EQUIPMENT, 257 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Wand", EQUIPMENT, 166 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Wand", EQUIPMENT, 258 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Pages", EQUIPMENT, 167 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Pages", EQUIPMENT, 259 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Shield", EQUIPMENT, 168 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Shield", EQUIPMENT, 260 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Helm", EQUIPMENT, 169 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Mail", EQUIPMENT, 170 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Mail", EQUIPMENT, 262 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Cap", EQUIPMENT, 171 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Cap", EQUIPMENT, 263 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Vest", EQUIPMENT, 172 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Vest", EQUIPMENT, 264 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Crown", EQUIPMENT, 173 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Crown", EQUIPMENT, 265 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Artisan Shirt", EQUIPMENT, 174 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Master Cape", EQUIPMENT, 266 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Short Spear", EQUIPMENT, 4 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Javelin", EQUIPMENT, 205 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Battle Scythe", EQUIPMENT, 6 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - War Scythe", EQUIPMENT, 208 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Short Bow", EQUIPMENT, 7 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Long Bow", EQUIPMENT, 209 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Stout Shield", EQUIPMENT, 45 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Iron Guard", EQUIPMENT, 68 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Vanguard", EQUIPMENT, 111 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Duelling Shield", EQUIPMENT, 215 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Sturdy Helm", EQUIPMENT, 26 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Copper Helm", EQUIPMENT, 69 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Bronze Helm", EQUIPMENT, 106 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Scale Helm", EQUIPMENT, 128 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Ring Mail", EQUIPMENT, 28 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Copper Suit", EQUIPMENT, 29 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Bronze Suit", EQUIPMENT, 107 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Scale Mail", EQUIPMENT, 127 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cotton Hood", EQUIPMENT, 32 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Holy Hat", EQUIPMENT, 33 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Holy Miter", EQUIPMENT, 109 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Silk Hat", EQUIPMENT, 110 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cotton Robe", EQUIPMENT, 20 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Mages Robe", EQUIPMENT, 21 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Priest Garb", EQUIPMENT, 216 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Silk Shirt", EQUIPMENT, 108 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Iron Sword", EQUIPMENT, 11 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Broadsword", EQUIPMENT, 12 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Sharp Sword", EQUIPMENT, 200 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Razor Edge", EQUIPMENT, 199 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Longsword", EQUIPMENT, 378 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Hand Axe", EQUIPMENT, 55 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Chopper", EQUIPMENT, 66 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Stone Splitter", EQUIPMENT, 201 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Broadaxe", EQUIPMENT, 383 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Stabbers", EQUIPMENT, 63 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Shank", EQUIPMENT, 60 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Kris", EQUIPMENT, 202 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Rondel", EQUIPMENT, 204 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Stinger", EQUIPMENT, 1 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Toothpick", EQUIPMENT, 42 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Estoc", EQUIPMENT, 207 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Scarlette", EQUIPMENT, 206 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cedar Staff", EQUIPMENT, 62 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Gnarled Root", EQUIPMENT, 15 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Quarterstaff", EQUIPMENT, 210 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Maplewood", EQUIPMENT, 211 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Cedar Wand", EQUIPMENT, 13 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Oak Wand", EQUIPMENT, 16 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Soul Wand", EQUIPMENT, 213 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Maple Wand", EQUIPMENT, 212 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Orylei", EQUIPMENT, 65 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Encyclopedia", EQUIPMENT, 214 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Beret", EQUIPMENT, 27 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Headgear", EQUIPMENT, 30 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Rugged Hat", EQUIPMENT, 219 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Vikings Hat", EQUIPMENT, 220 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Studded Armor", EQUIPMENT, 35 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Leather Mail", EQUIPMENT, 36 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Chain Vest", EQUIPMENT, 217 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Combat Vest", EQUIPMENT, 218 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Training Gi", EQUIPMENT, 229 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Fervor Charm", EQUIPMENT, 48 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Jewel of Defense", EQUIPMENT, 50 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Dodge Charm", EQUIPMENT, 39 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Protect Amulet", EQUIPMENT, 49 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Mana Ring", EQUIPMENT, 38 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Bracer", EQUIPMENT, 70 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Awake Ring", EQUIPMENT, 87 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Shell Amulet", EQUIPMENT, 179 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Samurais Glove", EQUIPMENT, 185 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Prayer Beads", EQUIPMENT, 186 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Fang Pendant", EQUIPMENT, 196 + equipment_index_offset, ItemClassification.useful),
        ItemData("Equipment - Scope Bit", EQUIPMENT, 226 + equipment_index_offset, ItemClassification.useful),
    ]
}