name: Feature Request
description: Request a feature!
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to see?
