name: Feature Request
description: Request a feature!
labels:
  - feature request
body:
  - type: markdown
    attributes:
      value: |
        Feature Request goes here!
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to see?
