name: Task
description: Submit a task to be done. If this is not targeting core, it should likely be elsewhere.
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: What task needs to be completed?
