CRYSTAL_LOCATION_GROUP = "Crystals"
HOME_POINT_LOCATION_GROUP = "Home Points"
REGION_COMPLETION_LOCATION_GROUP = "Region Completions"
SHOP_LOCATION_GROUP = "Shops"
#Fighting
BOSS_LOCATION_GROUP = "Bosses"
SUMMON_LOCATION_GROUP = "Summons"
#Collectibles
PENGUIN_LOCATION_GROUP = "Penguins"
CRAB_LOCATION_GROUP = "Undersea Crabs"